[package]
name = "brdgme-rand-bot"
version = "0.1.0"
authors = ["Michael Alexander"]
edition = "2018"

[dependencies]
brdgme-game = { git = "https://github.com/brdgme/game.git" }
brdgme-cmd = { git = "https://github.com/brdgme/cmd.git" }
rand = "0.3.15"
serde_json = "1.0.0"
chrono = "0.4.0"